### ISSUE TITLE
Webpack Error

### ISSUE THREAD

**Issue by mwunderlich** [alejandro-du/vaadin-microservices-demo#31] opened 2022-01-14 15:46 UTC
I tried to follow the tutorial, but already got stuck trying to start the initial services after cloning the repo. All seven services have started up correctly, but when I try to access localhost:8080, I get the following errors below. I have already run npm install and update npm to the latest version. No luck. 
(running on Mac OS 12.1 with Node 10.3.0 and OpenJDK 11.0.1)

ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/VaadinDevmodeGizmo.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 7:0-53
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/comboBoxConnector-es6.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 8:0-56
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/comboBoxConnector.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 72:0-52
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/contextMenuConnector-es6.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 9:0-59
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/contextMenuConnector.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 73:0-55
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/datepickerConnector.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 10:0-54
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/dndConnector-es6.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 11:0-51
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/dndConnector.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 74:0-47
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 12:0-58
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/gridConnector-es6.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 13:0-52
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/gridConnector.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 75:0-48
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/ironListConnector-es6.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 14:0-56
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/ironListConnector.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 76:0-52
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/ironListStyles.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 15:0-49
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/menubarConnector.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 16:0-51
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/selectConnector.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 77:0-50
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/timepickerConnector.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 17:0-54
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/vaadin-big-decimal-field.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 18:0-59
ERROR in ../target/frontend/generated-flow-imports.js
Module not found: Error: Can't resolve '@vaadin/flow-frontend/vaadin-grid-flow-selection-column.js' in '/Users/me/Dev/vaadin-microservices-demo/website-application/target/frontend'
 @ ../target/frontend/generated-flow-imports.js 19:0-68

**Comment by alejandro-du** [comment] 2022-03-16 19:03
Did you change the code? If not, maybe ask in the Vaadin Discord server.

**Comment by alejandro-du** [comment] 2022-03-16 19:04
Duplicate of #14

**Closed as completed by alejandro-du** 2022-03-16 19:04 UTC
